server:
  port: 8080

spring:
  application:
    name: jb2dev-cv-api
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO
    com.jb2dev.cv: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId:-NO-CORRELATION-ID}] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,loggers
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true

springdoc:
  api-docs:
    path: /api/v1/openapi
  swagger-ui:
    path: /api/v1/swagger-ui
